apiVersion: v1
kind: Service
metadata:
  name: Ect-Webserver-Service
  labels:
    name: Ect-webserver
    app: Ect-webserver
spec:
  selector:
    name: Ect-webserver
  ports:
   - port: 8080
     name: http
     targetPort: 8080